# Generated by Django 2.2.26 on 2022-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reprepro', '0005_auto_20151225_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='all_distributions',
            field=models.BooleanField(default=False, help_text='If set, the package will be automatically added to all known distributions with same vendor.'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='vendor',
            field=models.SmallIntegerField(choices=[(0, 'Debian'), (1, 'Ubuntu'), (2, 'Fedora'), (3, 'RedHat')]),
        ),
    ]
