# Generated by Django 2.2.26 on 2022-01-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reprepro', '0006_auto_20220119_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
