# Generated by Django 1.9 on 2015-12-25 14:06
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repomanager', '0003_auto_20151225_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=32)),
                ('arch', models.CharField(max_length=8)),
                ('components', models.ManyToManyField(to='repomanager.Component')),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repomanager.Distribution')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repomanager.Package')),
            ],
        ),
        migrations.RemoveField(
            model_name='sourcepackage',
            name='arch',
        ),
    ]
